global using BenchmarkDotNet.Analysers;
global using BenchmarkDotNet.Columns;
global using BenchmarkDotNet.Configs;
global using BenchmarkDotNet.Diagnosers;
global using BenchmarkDotNet.Jobs;
global using BenchmarkDotNet.Loggers;
global using BenchmarkDotNet.Running;
global using BenchmarkDotNet.Validators;
global using Xunit;
